---

- name: Upgrade all packages to the latest
  apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - vim
    - curl
    - wget
    - openssl
    - sysstat
    - nmap
    - scapy
    - git
